### ISSUE TITLE
Add link to Register screen from Login screen Android App

### ISSUE THREAD

**Issue by xxxcucus** [xxxcucus/planes#21]
I would like to have the possibility to jump from the Login screen directly to the Register screen.
There should be a button in the Login screen with the following text:
"New user? Please register" and by clicking on it one should be redirected to the 
Register screen.
Changes should be made to the portrait and landscape layouts for the login.

**Comment by jmanan088** [comment]
Hey! Is this issue regarding the android version? If so I would like to try to solve this.

**Comment by xxxcucus** [comment]
Yes it is regarding the Android version.

**Comment by Tc2r1** [comment]
> Hello, I'll fix this issue. May you assign it to me?

Nice Job bro, Love you.
