### ISSUE TITLE
Feature Request: Implement "Draw" System

### ISSUE THREAD

**Issue by AoiSeaghdha** [xxxcucus/planes#4]
Often-times the player and computer can kill each other on the same turn. However, this defaults to a Computer Wins, which is player-unfriendly - contextually, either the player is "playing first" or both are playing at the same time, and thus it should either result in either a Player Wins, or in a Draw. Personally, I find the idea of a Draw more appealing.

**Comment by Go-rom** [comment]
Hello,

i totally agree with this feature request.

It could end with a draw (no one gets the point or 1 point each other)
Another end could be one point to the player with the the highest hits. If both players get the same hits number then it could be the lowest misses.

**Comment by xxxcucus** [comment]
Feature added in Release 0.3.9. Thanks! Let me know how it works!
