### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [xxxcucus/planes#40]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3971794639#L1457

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/1b7972667dd9acb53adf27f5761a178841c22f90

**Comment by xxxcucus** [comment]
I have updated the kotlin gradle plugin version. Could you please try again ?

**Comment by licaon-kter** [comment]
Done, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/cd2a8cdb59564d791357a01fe35196b134f7f376
