### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by meyou69** [xxxcucus/planes#42]
Salut,

Acesta nu este tocmai un issue.

Vroiam doar să-ți mulțumesc că ai implementat jocul ăsta pe Android și că l-ai făcut și open source și l-ai publicat pe F-Droid.

Puțin fac asta. Dacă vrei, poți să adaugi și un link de donații pe F-droid, pentru cei care vor dori să-ți doneze. 

Poți închide issue-ul ăsta

**Comment by xxxcucus** [comment]
Multumesc pt aprecieri
