### ISSUE TITLE
Create an .xml layout for the "Delete User" function

### ISSUE THREAD

**Issue by xxxcucus** [xxxcucus/planes#43]
This layout should be similar in functionality with the layout for "Logout" screen. When the user is not logged in it should say that the user is not logged in and the "Delete User" Button should not be active. When the user is logged in the same text indicating that the user had logged in the "Logout" screen should be displayed and the button should be active.

**Comment by utkarsh006** [comment]
@xxxcucus assign me this issue.

**Comment by xxxcucus** [comment]
@uktarsh006 Somehow Github doesn not let me assign this to you. Just make a pull request and I will merge.

**Comment by utkarsh006** [comment]
@xxxcucus Sure, I'll try to raise a PR as I get free.

**Comment by xxxcucus** [comment]
implemented
