### ISSUE TITLE
Feature request: 1v1 play on one device

### ISSUE THREAD

**Issue by micwoj92** [xxxcucus/planes#8]
Basically like the board game. My suggestion is to add confirmation or delay so accidental touches could be prevented.

**Comment by xxxcucus** [comment]
Have you tried version 0.3.8? Here touch only counts if it is made on a single square in the board. Other swipe like movements are  for guessing discarded.

**Comment by micwoj92** [comment]
Yes, but in terms of 1v1 play you still could accidentally tap two times and make move for your opponent.

**Comment by xxxcucus** [comment]
Can you explain a bit what you mean by 1v1 play? Once you have guessed on a grid square you cannot guess again. Even if touch very fast.

**Comment by micwoj92** [comment]
1 human player vs another human player.
It could be possible to implement it in 2 ways:
1. 2 small boards
2. 1 board which would switch after a move (the problem would affect this)

**Comment by xxxcucus** [comment]
I understand your concerns.  A multiplayer version will come in the next year and it will work as you expected
